FlagOpen/FlagScale

tools/convert.py
tools/loader_megatron.py
tools/loader_transformers.py
tools/mixtral/args.py
tools/mixtral/ckpt.py
tools/mixtral/model.py
tools/run.sh
tools/saver_megatron.py

- loader_transformer: load complete (no parallel) ckpt file
- loader_megatron: can load parallel-ckpt file, support tp, pp, vpp and moe
- saver_megatron: can save parallel-ckpt file, support tp, pp and moe
- example:
```bash
cd tools
python convert.py \
--model-type mixtral \
--loader transformer \
--saver megatron \
--load-dir Mixtral-8x7B-v0.1 \
--save-dir output \
--target-tensor-parallel-size 2 \
--target-pipeline-parallel-size 2 \
--target-expert-parallel-size 2 \
```
- support vpp save
- add saver_transformer
- add aquila transfer

add loader_transformer, loader/saver_megatron

---

flagscale/launcher/runner.py

Using this fix, we can set a flag to false instead of removing it. in the yaml file. For example,  you can use `flag: false` instead of commenting out `# flag: true`.

Fix a minor bug

---

.coveragerc
.github/workflows/approve.yml
.github/workflows/review.yml
.github/workflows/test.yml
tests/scripts/unit_test_flagscale.sh
tests/scripts/unit_test_megatron.sh

- Could view test coverage report online.
- Need specific user review.

Add the test coverage report and reviewer check

---

flagscale/auto_tuner/prune/history.py
flagscale/auto_tuner/record/recorder.py
flagscale/auto_tuner/search/searcher.py
flagscale/auto_tuner/tuner.py
flagscale/auto_tuner/utils.py
flagscale/launcher/runner.py

In this PR, we optimize prune rules:
1. adding prune rules based on tp and pp
2. adding dist optimizer rules
3. adding Multi-Dimensional joint rules.
Pruning rules now cover dist optimizer, mbs, sp, recompute, tp, pp, and any combination between them

[AutoTuner]Optimize prune and fix some bugs

---

.github/workflows/format.yml
.github/workflows/test.yml
.pre-commit-config.yaml
flagscale/auto_tuner/generate.py
flagscale/auto_tuner/prune/history.py
flagscale/auto_tuner/prune/pruner.py
flagscale/auto_tuner/record/recorder.py
flagscale/auto_tuner/search/algorithm.py
flagscale/auto_tuner/search/searcher.py
flagscale/auto_tuner/tuner.py
flagscale/auto_tuner/utils.py
flagscale/datasets/sft_dataset.py
flagscale/launcher/runner.py
flagscale/logger.py
flagscale/patches_utils.py
megatron/tests/unit_tests/__init__.py
tests/scripts/functional_test_flagscale.sh
tests/scripts/unit_test_flagscale.sh
tests/scripts/unit_test_megatron.sh

- format.yml for online check.
- .pre-commit-config.yaml for commit check.

Add format check

---

flagscale/auto_tuner/memory_model.py
flagscale/auto_tuner/platform.py
flagscale/auto_tuner/prune/memory.py
flagscale/auto_tuner/prune/pruner.py
flagscale/auto_tuner/search/algorithm.py
flagscale/auto_tuner/search/searcher.py
flagscale/auto_tuner/tuner.py
flagscale/auto_tuner/utils.py
flagscale/train/theoretical_memory_usage.py

This PR adds memory model, which can be used to speed up pruning and filter out OOM memory strategies and strategies with low memory usage.

[AutoTuner]Add memory model

---

examples/llava/conf/train/train_llava1.5_7b.yaml

This PR removes the `img_embedding_idx ` for llava due to latest llava doesn't need it.

[Bug Fix] Remove img_embedding_idx config

---

examples/llama/conf/config.yaml
examples/llama/conf/train/train_llama3_70b_finetune.yaml
examples/llava/conf/config.yaml
examples/llava/conf/train/train_llava1.5_7b.yaml
examples/mixtral/conf/config.yaml
examples/mixtral/conf/train/train_mixtral_8x7b.yaml
megatron/examples/multimodal/mlp_converter.py
tools/checkpoint/llama/args.py
tools/checkpoint/run.sh

This PR adds mlp ckpt conversation from hf to megatron in the llava pretrain phase.
An tp2 example of the ckpt conversation for the LLaVA Pretrain phase is shown below:
- CLIP
`
cd FlagScale/megatron && python examples/multimodal/clip_converter.py --download-root <clip_hf_dir>  --output <clip_megatron_dir> --tensor-parallel-size 2 --use-te-layernorm-linear
`
- Vicuna
`
cd FlagScale/megatron && python tools/checkpoint/convert.py --model-type GPT --loader llama_mistral --saver mcore --target-tensor-parallel-size 2 --checkpoint-type hf --load-dir <vicuna_hf_dir> --save-dir <vicuna_megatron_dir> --tokenizer-model <vicuna_hf_dir>/tokenizer.model --bf16 --model-size llama2-7Bf --true-vocab-size 32256 --megatron-path <flagscale_dir>
`
- MLP
`
cd FlagScale/megatron && python …

[Model] Add llava mlp converter and update three models config

---

.github/workflows/test.yml

Compared with the common ancestor of the main branch during pull_request for unit-test coverage testing of newly added code.

[CI] Only perform unit-test coverage checks when pull_request.

---

megatron/megatron/core/transformer/transformer_block.py

Move the recompute configuration code from the `_checkpointed_forward` to `forward`.
Deal with the recompute configuration when `recompute_num_layers_per_stage_micro_batch` has `0` layers.

[Hetero] Polish recompute strategy

---

flagscale/runner/runner_inference.py

Fixed import error caused by the vllm file name in root_path being the same as the installation package name.
Cherry-pick from https://github.com/FlagOpen/FlagScale/pull/266

[CherryPick][BugFix] fix import vllm error (#266)

---

flagscale/runner/runner_utils.py
megatron/megatron/core/dist_checkpointing/serialization.py
megatron/megatron/core/dist_checkpointing/strategies/filesystem_async.py
megatron/megatron/core/dist_checkpointing/strategies/torch.py
megatron/megatron/core/transformer/transformer_block.py
tests/scripts/format_tests/test_format.sh
tools/checkpoint/sfpt_ckpt/README.md
tools/checkpoint/sfpt_ckpt/dcp_to_sfpt.py
tools/checkpoint/sfpt_ckpt/sfpt_to_dcp.py

This PR contains the changes for converting checkpoints between DCP (Distributed Checkpoint) and SFPT (Single File Per Tensor) formats.

[Core] Add the conversion between dcp and sfpt

---

.github/workflows/coverage-tests.yml
.github/workflows/unit-tests.yml

Output the address information of the test report in advance, so that the address information of the report can still be output in case of unit test failure or test coverage failure.

[CI] Coverage Online Report Location Advance

---

flagscale/auto_tuner/record/recorder.py
flagscale/runner/runner_train.py

I want to change the default metric to TFLOPs and change the order to descend, but it doesn't work. Because, the "auto_tuner" is under config.experiment instead of config.
After making the following changes it worked.
Change
if (
"auto_tuner" in self.config
and "performance" in self.config.experiment.auto_tuner
):
to
if (
"auto_tuner" in self.config.experiment
and "performance" in self.config.experiment.auto_tuner
):

[Fix] "auto_tuner" should be under the field config.experiment.

---

flagscale/train/extra_valid.py
flagscale/train/train.py
flagscale/train/train_aquila.py
flagscale/train/train_aquila_sft.py
flagscale/train/train_llama.py
flagscale/train/train_mixtral.py
megatron/megatron/training/arguments.py

1. usage:
```yaml
extra_eval_interval: 5
extra_valid_data_path: [
weight1, data_path1,
weight2, data_path2,
]
```
- `weight` refers to the number of tokens for extra validation in `data_path`.
- **NOTE: The extra validation always starts from consumed_sample=0.**
2. output format
```
(min, max) time across ranks (ms):
evaluate .......................................: (xxx, xxx)
-------------------------------------------------------------------------------
extra validation iteration 5 loss at data_path1 | consumed samples: xxx | lm loss value: xxx | lm loss PPL: xxx | 
-------------------------------------------------------------------------------
(min, max) time across ranks (ms):
evaluate .......................................: (xxx, xxx) …
```

update extra validation feature

---

megatron/megatron/core/transformer/moe/moe_utils.py
megatron/megatron/core/transformer/moe/router.py
megatron/megatron/core/transformer/transformer_config.py
megatron/megatron/training/arguments.py

Support sigmoid router in moe similar to DeepSeek V3
- add a configuration str <moe_router_score_function_type> in TransformerConfig
- support using sigmoid+normalization to compute prob scores
The implementation in this PR, is similar to that in DeepSeek V3, as shown in the figure below. Scores are first calculated using a sigmoid for x, and then the topk function is used to select the k largest scores, finally the k scores are averaged.
Currently, sigmoid router is supported for two load balancing types: auxiliary loss and sequence auxiliary loss.
We will support auxiliary loss free load balancing in the future.
references to: https://github.com/deepseek-ai/DeepSeek-V3/blob/main/DeepSeek_V3.pdf

[Core] Support sigmoid router for aux_loss in moe

---

tests/unit_tests/test_sigmoid_aux_loss.py

Add a unit test for moe sigmoid router, including tests for two load balancing strategy: aux_loss and seq_aux_loss.
ref pr #310 
CI已触发

Add unit test for moe sigmoid router

---

flagscale/train/__init__.py
flagscale/train/global_vars.py
flagscale/train/spiky_loss.py
flagscale/train/train.py
flagscale/train/train_aquila.py
megatron/megatron/training/arguments.py
megatron/megatron/training/initialize.py
tests/functional_tests/test_cases/hetero_train/aquila/conf/train/tp2pp1_tp4pp1_tp2pp1.yaml
tests/unit_tests/test_spiky_loss_detector.py

Support to skip samples according to spiky loss. There are two methods to skip samples:
1.    You can manually set the skipping range
```
skip_samples_range: [20, 30]
```
2.    Automatically detect the spiky loss and skip the samples
```
auto_skip_spiky_loss: true
spiky_loss_threshold: 0.25
```

[Core] Support to skip samples according to spiky loss

---

flagscale/runner/runner_serve.py

Improvement
in config.yaml, specify **nproc_per_node** and **device_type** on target device.
Note: config key  **device_type** is specified for _**single node serving**_ in neither gpu or cpu. In **_multiple nodes_** case, use config key **hostfile** instead.
```
experiment:
runner:
nproc_per_node: 8
device_type: xxx
```

[Serve] serve supports other device more than gpu and cpu

---

megatron/megatron/core/dist_checkpointing/exchange_utils.py
megatron/megatron/core/dist_checkpointing/mapping.py
megatron/megatron/core/dist_checkpointing/validation.py

np.product was deprecated in NumPy 1.25.0 and was removed in NumPy 2.0.

[Megatron-LM] Update np.product to np.prod

---

__init__.py
flagscale/cli.py
flagscale/runner/runner_serve.py
flagscale/serve/run_vllm.py
setup.py

This PR introduces the flagscale CLI. To install it, navigate to the FlagScale directory and run:
`cd FlagScale && pip install .`
The `examples` will be packaged.
To uninstall, simply run:
`pip uninstall flag_scale`
Currently, the flagscale CLI supports the serve command.
To serve a model using flagscale, run:
`flagscale serve deepseek_r1 <yaml_path>` or 'flagscale serve deepseek_r1'
NOTE: If u want to use `flagscale serve model_name` to serve model, u should modify the `examples` to add your moedel yaml. Then run `pip install .`

[Core] Add FlagScale CLI

---

docker/Dockerfile.cuda
flagscale/cli.py

This PR introduces the `flagscale pull` command, which allows users to pull Docker images and download checkpoints (ckpt) from a specified Git repository.
First, please install FlagScale:
```bash
cd FlagScale && pip install .
```
The command for pulling images and checkpoints, along with setting the storage path for checkpoints, is as follows:
```bash
flagscale pull [--image <image>] [--ckpt <ckpt>] [--ckpt-path <ckpt_save_path>]
```
- `--image`: Optional. Docker image address that you want to pull.
- `--ckpt`: Optional. The Git repository address of the checkpoint you wish to download.
- `--ckpt-path`: Optional. If provided, the checkpoint will be stored in the specified path. If not set, it will be downloaded to a folder named `model_download` in the current directory.

[CLI] Add flagscale pull command

---

megatron/megatron/core/model_parallel_config.py
megatron/megatron/core/parallel_state.py
megatron/megatron/training/arguments.py

Change the default value of  `pipeline-model-parallel-comm-backend` to `None` to support the `distributed-backend` is not `nccl`.

[Core] Fix ucc comm-backend when using `FlagCX` backend

---

flagscale/cli.py
setup.py

This PR sets the requirements of the cli installation, and we improve ease of use:
- flagscale pull just on host machine, so we moved some imports into concrete functions
- To avoid installation error on the CPU without GPU, we fix the exception

[CLI] Add requirements and improve ease of use

---

flagscale/cli.py
setup.py

This PR sets the requirements of the cli installation, and we improve ease of use:
- flagscale pull just on host machine, so we moved some imports into concrete functions
- To avoid installation error on the CPU without GPU, we fix the exception

[CherryPick][CLI] Add requirements and improve ease of use (#381)

---

flagscale/runner/auto_tuner/memory_model.py
run.py

To accommodate the scenario where the before_start field is used to switch to the actual environment during program execution,  we have placed the import statements inside the function body rather than at the beginning of the file.

[Core] Fix import error

---

requirements/train/megatron/requirements-cuda.txt

Split into two parts for merging:
1. First merge: Update the training requirements, add the package required for llava_onevision training, and obtain the commit ID after merge.
2. Second merge: Update the image with the updated requirements, mark the image with the first merge commit ID, and submit the llava_onevision test.

[CI] Update requirements for llava_onevision training

---

examples/deepseek_v3/conf/config_deepseek_v3.yaml
examples/deepseek_v3/conf/train/train_deepseek_v3.yaml
flagscale/train/train_deepseek_v3.py
tools/checkpoint/deepseek_v3/args.py
tools/checkpoint/deepseek_v3/ckpt.py
tools/checkpoint/deepseek_v3/model.py
tools/checkpoint/loader_mcore.py
tools/checkpoint/loader_transformers.py
tools/checkpoint/run.sh
tools/checkpoint/saver_mcore.py
tools/checkpoint/saver_transformers.py

[Tools] Support for ckpt conversion of deepseek v3

---

.github/workflows/all-tests.yml
install/install-requirements.sh

1. Update CI images to flagscale:cuda-12.4.1-python-3.12-torch-2.5.1-commit-e05f659, the main modification is the update to the TE version, and the corresponding commit can be viewed.
3. Install requirements-lint.txt outside of the conda environment, to resolve the issue of not being able to find diff-cover command.
4. Manually apply modifications to images flagscale:cuda-12.4.1-python-3.12-torch-2.5.1-commit-e05f659.

[CI] Update CI images

---

flagscale/runner/estimator/meta_attention.py
flagscale/runner/estimator/meta_base.py
flagscale/runner/estimator/meta_gpt.py
flagscale/runner/estimator/meta_mlp.py
flagscale/runner/estimator/meta_modules.py
flagscale/runner/estimator/meta_transformer_layer.py
flagscale/runner/estimator/utils.py
tests/unit_tests/runner/estimator/test_meta_attention.py
tests/unit_tests/runner/estimator/test_meta_base.py
tests/unit_tests/runner/estimator/test_meta_gpt.py
tests/unit_tests/runner/estimator/test_meta_mlp.py
tests/unit_tests/runner/estimator/test_meta_modules.py
tests/unit_tests/runner/estimator/test_meta_transformer_layer.py
tools/estimator/estimate_gpt.py

This PR introduces a new estimator folder with modules for estimating model resource usage. It provides:
- Theoriatical estimation for parameters, FLOPs, and activations.
- Utilities for computing memory requirements and printing results.
- Configurations and modules (attention, MLP, transformer) to simulate large models (e.g., GPT).
- These additions help analyze memory and compute demands during model design and scaling.
- Support data parallelism, tensor parallelism ,and pipeline parallelism.
Users can use this tool on their PCs without the need for a GPU.
```
cd FlagScale/tools
python estimate_gpt.py
```

[Core] Add a general estimator

---

examples/aquila/conf/train/train_aquila_3b.yaml
examples/deepseek_v3/conf/train/train_deepseek_v3_hetero.yaml
flagscale/train/arguments.py
flagscale/train/hetero/parallel_context.py

1. Fix the bug that we can't use `expert_tensor_parallel_size_per_process_mesh` to set `expert_tensor_parallel_size` in hetero mode in https://github.com/FlagOpen/FlagScale/pull/395
2. Update the `Aquila-3B` configuration.

[Fix] Fix hetero etp & update aquial_3B config

---

flagscale/train/theoretical_memory_usage.py
flagscale/train/train.py
megatron/megatron/training/theoretical_memory_usage.py

- Polish theoretical_memory_usage:
- add activated weight number theoretical computation of MoE and MLA
- add weight&optimizer memory theoretical computation of MoE and MLA
- add activation memory theoretical computation of MoE and MLA
- support expert parallel, tensor parallel, and expert tensor parallel
- Result:
- **[CASE-1] Qwen2.5-16b, tensor_model_parallel_size=4, sequence_parallel=True**
* **Theoretical result:**
```
> Number of attn parameters in a transformer block in billions:  0.06
> Number of dense mlp parameters in a transformer block in billions:  0.21
> Number of sparse mlp parameters in a transformer block in billions:  0.00
> Number of parameters in transformer block in billions:  14.86
> Number of parameters in mtp transformer block in billions:  0.00
> Number of …
```

[Core] Add theoretical_memory_usage and FLOPs computation for DeepSeekMoE

---

setup.py
tools/datasets/llava_onevision/llava_ov_wds.py
tools/datasets/llava_onevision/make_llava_ov_wds.sh

This PR accelerates the data preprocessing of Llava OneVision. It adopts a multi-task approach, launching multiple tasks simultaneously for processing, with each task handling a portion of the data. In practical tests, it can achieve an acceleration of more than twice in the single image scenario, and an acceleration of up to 1.4 times in the video and multi-image scenarios.
Usage: set task count by `twice` in  `make_llava_ov_wds.sh`

[Tools] Speed up the llavaov data preprocess

---

examples/aquila/conf/config_inference.yaml
flagscale/backends/vllm/pyproject.toml
flagscale/backends/vllm/requirements/build.txt
flagscale/backends/vllm/vllm/core/scheduler.py
flagscale/backends/vllm/vllm/distributed/device_communicators/pynccl_wrapper.py
flagscale/backends/vllm/vllm/distributed/kv_transfer/kv_connector/factory.py
flagscale/backends/vllm/vllm/engine/llm_engine.py
flagscale/backends/vllm/vllm/inputs/data.py
flagscale/backends/vllm/vllm/inputs/preprocess.py
flagscale/backends/vllm/vllm/model_executor/models/registry.py
flagscale/backends/vllm/vllm/sampling_params.py
flagscale/backends/vllm/vllm/sequence.py
flagscale/backends/vllm/vllm/worker/model_runner.py

[vLLM] Update to v0.8.5

---

flagscale/backends/Megatron-LM/megatron/training/checkpointing.py
hardware/README.md
hardware/README_CN.md
tools/patch/encryption_utils.py
tools/patch/file_utils.py
tools/patch/git_utils.py
tools/patch/logger_utils.py
tools/patch/patch.py
tools/patch/unpatch.py

This PR adds patch encryption, which can be used with the command `python tools/patch/patch.py --key-path`, and for decryption with` python tools/patch/unpatch.py --key-path.` In addition, this PR further improves the usability of the patch mechanism, including: 
- Support for fuzzy matching of backend inputs, for example, Megatron-LM can be entered as megatron or megatron-lm.
- The patch generation process has been enhanced to support modifications involving subtrees.
- When the vendor performs `unpatch`, if neither `patch_history.yaml` is present nor the `commit` parameter is provided, the patch file from the current commit will be used for unpatching by default.
- Automatic check for Git config has been added.

[Tools] Add patch encryption and enhance patch usability

---

tools/patch/git_utils.py
tools/patch/patch.py
tools/patch/unpatch.py

This PR adds the ability to specify a commit for the submodule and optionally apply the FlagScale adaptation. Usage is as follows:
`python tools/patch/unpatch.py --backend vllm --backend-commit <vllm_commit> --no-fs-extension`
`--backend-commit` indicates the commit to which the submodule will automatically reset after a submodule update. The `--no-fs-extension` means the FlagScale adaptation will not be applied, and the submodule will remain in its original state.

[Tools] Support specified submodule commit for hardware patch

---

custom_build_backend/flagscale_build_backend.py
pyproject.toml
setup.py

This PR updates the installation mechanism of FlagScale. Usage is as follows:
`cd FlagScale`
`PYTHONPATH=./:$PYTHONPATH pip install . --config-settings=backend=<backend> --config-settings=device=<device>  --verbose --no-build-isolation`
The `backend` parameter can accept multiple values, separated by commas, such as "vllm,sglang,llama.cpp"

[Core] Update FlagScale setup

---

hardware/patch_history.yaml
tools/patch/merge.py
tools/patch/unpatch.py

This PR adds the patch history yaml for hardware and use `python tools/patch/merge.py --backend vllm FlagScale --task inference --device-type <device> --commit <merged_in_flagscale_commit>` to add information.

[Tool] Add patch history yaml

---

examples/cloud/conf/serve.yaml
examples/cloud/conf/serve/cloud_model.yaml
flagscale/runner/runner_serve.py
flagscale/runner/utils.py
run.py

In each node, run same below command
```
docker run -it \
--name cloud \
--privileged \
--gpus all \
--net=host \
--ipc=host \
--device=/dev/infiniband \
--shm-size 512g \
--ulimit memlock=-1 \
-v /mnt/xxx/workspace:/workspace \
-v /mnt/xxx/models:/models \
--env MASTER_ADDR=xxx \
--env AIRS_ACCELERATOR_NUM=8 \
flagscale_maas:v1 \
/bin/bash -c "flagscale serve cloud --model-path /model/qwen --port 8000 --engine-args='{"tensor_parallel_size":4}'; tail -f /dev/null"
```
**Note:**
required args for user: --model-path
optional args for user: --port, --engine-args
**Serve API:**
serve API as OpenAI style : `http://{MASTER_ADDR}:{PORT}`

[Serve] Support cloud serving

---

examples/cloud/conf/serve.yaml
examples/deepseek_v3/conf/serve_auto_tuner.yaml
examples/qwen2_5/conf/serve.yaml
examples/qwen2_5/conf/serve_auto_tuner.yaml
examples/qwen2_5/conf/serve_disagg_xpyd.yaml
examples/qwen2_5/conf/serve_multiple_instance.yaml
examples/qwen3/conf/serve.yaml
examples/qwen3/conf/serve_atmb.yaml
examples/robobrain/conf/serve.yaml
flagscale/runner/auto_tuner/generate.py
flagscale/runner/auto_tuner/tuner.py
flagscale/runner/runner_serve.py
flagscale/serve/run_disagg_xpyd_router.py
flagscale/serve/run_fs_serve_vllm.py
run.py

'config.experiment.deploy' has been moved to 'config.experiment.runner.deploy'. Support of old deploy location will be removed in future.
Todo:

[Serve] Move config.experiment.deploy into config.experiment.runner.deploy

---

examples/robobrain2/conf/serve.yaml
examples/robobrain2/conf/serve/32b.yaml
examples/robobrain2/conf/serve/7b.yaml

This PR update adds support for the inference deployment of 7B and 32B embodied intelligence models for RoboBrain2.

Support the deployment of RoboBrain2 models in both 7B and 32B configuration

---

.gitmodules
examples/qwen2/conf/rl.yaml
examples/qwen2/conf/rl/7b.yaml
flagscale/runner/runner_rl.py
flagscale/runner/utils.py
run.py
tools/patch/patch.py

Please add "verl" as a new reinforcement learning (RL) backend and implement the following changes:
1. Implement patch and unpatch support for the "verl" backend.
2. Create a new submodule named "verl."
3. Introduce a new task type called "rl" in the `run.py` file.
4. Call the `SSHRLRunner` in the `runner_rl.py` file.
5. Include an example configuration.

[Backend] Add verl as the rl backend

---

.github/workflows/coverage-tests.yml
.github/workflows/functional-tests.yml
.github/workflows/report-clean.yml
.github/workflows/unit-tests.yml

Use complete labels to specify the runner to distinguish test tasks on different hardware.

[CICD][Runner] Use full labels to specify the runner

---

flagscale/agent/collaboration/collaborator.py

- Added methods to store environment objects and agent state in Redis hash
- Implemented read_environment() to retrieve ENVIRONMENT_INFO
- Implemented record_environment() to update specific ENVIRONMENT_INFO fields
- Unified JSON serialization/deserialization for all Redis values

[Agent] Add environment info record/read
