FlagOpen/FlagScale

apu_demo/scripts/pretrain_aquila_7b_distributed_extra.json, aquila/7B/pretrain_aquila_7b_distributed.json, predefined_args_megatron.json, run.py
- Unify the configuration based on json
- Unify the local and distributed launch based `run.py` and configuration.
=> Unify the config and runner

examples/llama2/README.md, examples/llama2/train_llama2_70b_distributed.sh, examples/pretrain_llama2_distributed.sh, megatron/model/__init__.py, megatron/model/llama_model.py, megatron/optimizer/__init__.py, pretrain_llama.py
=> Add llama2-70B standard case

megatron/megatron/arguments.py, megatron/megatron/tokenizer/tokenizer.py
=> support huggingface tokenizer

ascend/README.md, ascend/patches/__init__.py, ascend/patches/adaptor_arguments.py, ascend/patches/adaptor_core_models_common_rotary_pos_embedding.py, ascend/patches/adaptor_core_tensor_parallel_cross_entropy.py, ascend/patches/adaptor_core_tensor_parallel_layers.py, ascend/patches/adaptor_core_tensor_parallel_random.py, ascend/patches/adaptor_core_utils.py, ascend/patches/adaptor_initialize.py, ascend/patches/adaptor_model_fused_layer_norm.py, ascend/patches/adaptor_model_fused_softmax.py, ascend/patches/adaptor_model_module.py, ascend/patches/adaptor_model_transformer.py, ascend/patches/adaptor_optimizer_clip_grads.py, ascend/patches/adaptor_optimizer_distrib_optimizer.py, ascend/patches/adaptor_optimizer_optimizer.py, ascend/patches/adaptor_p2p_communication.py, ascend/patches/adaptor_schedules.py, ascend/patches/ascend_turbo/README.md, ascend/patches/ascend_turbo/__init__.py, ascend/patches/ascend_turbo/ascend_turbo_cfg.py, ascend/patches/ascend_turbo/initialize.py, ascend/patches/ascend_turbo/mc2_linears_seq_parallel.py, ascend/requirements.txt, ascend/scripts/pretrain_aquila_7B_distributed_extra.json, megatron/megatron/arguments.py, megatron/megatron/initialize.py, megatron/megatron/optimizer/clip_grads.py, megatron/megatron/optimizer/optimizer.py, megatron/megatron/utils.py
Update ascend/pathes
Update ascend/scripts with Aquila2-7B
Update ascend/README.md
Modify megatron/megatron/arguments.py with Ascend arguments
Modify megatron/megatron/initialize.py with Ascend patches
Modify megatron/megatron/optimizer and utils.py with try catch "import amp_C"
=> [Ascend] Support Aquila2 training with Ascend NPU

flagscale/extra_valid.py, megatron/megatron/arguments.py, megatron/megatron/tokenizer/tokenizer.py, megatron/megatron/training.py, megatron/pretrain_gpt.py
- Introduce a functionality to perform real-time evaluation on user-supplied extra validation datasets.
- Resolve the problem related to the `log_freq` parameter in the WandB integration.
- Update `hf_tokenizer` to  `tokenizer_path` for enhanced clarity and consistency.
=> Add the real-time validation feature

flagscale/train/stablelm2_scheduler.py, megatron/megatron/training/arguments.py, megatron/megatron/training/optimizer_param_scheduler.py, megatron/megatron/training/training.py
Add schedulers of MiniCPM & StableLM2.
=> Add schedulers of MiniCPM & StableLM2.

.github/workflows/test.yml, megatron/megatron/core/datasets/blended_megatron_dataset_builder.py, megatron/megatron/training/global_vars.py, megatron/tests/unit_tests/data/__init__.py, megatron/tests/unit_tests/data/test_builder.py, megatron/tests/unit_tests/data/test_gpt_dataset.py, megatron/tests/unit_tests/data/test_multimodal_dataset.py, megatron/tools/preprocess_data.py, tests/scripts/unit_test_megatron.sh
- Add local cache of nltk_data.
- Add set_mock_args.
=> pass tests/unit_tests/data

.github/workflows/test.yml
=> [CI] Add proxy

examples/llama/conf/config.yaml, examples/llama/conf/train/train_llama3_70b.yaml
Command
`python run.py --config-path ./examples/llama/conf --config-name config`
References
- https://ar5iv.labs.arxiv.org/html/2407.21783
=> [Llama3] Add llama3 70b training configuration yaml

examples/llama/conf/train/train_llama3_70b.yaml, examples/mixtral/conf/train/train_mixtral_8x7b.yaml
Add the ckpt_format parameter to   train_llama3_70b.yaml  and  train_mixtral_8x7b.yaml .
=> [BugFix] Add ckpt_format to yaml

examples/llama/conf/train/train_llama3_70b.yaml, examples/llama/conf/train/train_llama3_70b_finetune.yaml, examples/mixtral/conf/train/train_mixtral_8x7b.yaml
This PR adds mixtral tokenizer type and update llama config.
=> [Model] Update mixtral and llama config

flagscale/train/hetero/p2p_communication.py, flagscale/train/hetero/parallel_context.py, megatron/megatron/core/parallel_state.py, megatron/megatron/core/pipeline_parallel/p2p_communication.py
1. Fix p2p comm in the hetero scenario because the commit https://github.com/NVIDIA/Megatron-LM/commit/8af3dae72a944848db0122047d89e04ab078b178
2. Change the `parallel_context` to support `ulysses sequence parallel`.
=> [Hetero] Fix p2p comm in the hetero scenario

hardware/cambricon_MLU/085811f4/085811f4.patch
基于FlagScale commit：085811f4，按照patch格式添加对llava1.5_7b的支持。
=> [cambricon] Support for llava1.5_7b with patch

hardware/metax_C500/237377e9/237377e9.patch
[metax] add mixtral-8x7b flagscale continue train patch
=> [metax] add mixtral-8x7b flagscale continue train patch

.github/workflows/test.yml, examples/aquila/conf/config_inference.yaml, examples/aquila/conf/inference/inference_aquila_7b.yaml, flagscale/auto_tuner/tuner.py, flagscale/auto_tuner/utils.py, flagscale/inference/inference_aquila.py, flagscale/launcher/job_status.py, flagscale/runner/runner_base.py, flagscale/runner/runner_inference.py, flagscale/runner/runner_train.py, flagscale/runner/runner_utils.py, run.py, tests/scripts/unit_tests/config.yml, tests/unit_tests/runner/test_parse_hostfile.py
To improve future extensibility, split the `runner.py` into `runner_base.py`, `runner_train.py`, `runner_inference.py`, and `runner_utils.py`.
=> [Core] Refactor the runner

examples/llama/conf/train/train_llama3_8b.yaml, megatron/megatron/training/checkpointing.py
Fix bug during loading kept if enabling CPU communication
=> [Hetero] Fix bug during loading ckpt if enabling CPU communication

flagscale/runner/runner_train.py, flagscale/runner/runner_utils.py
Support to set environment variables according to device type
```
envs:
CUDA_VISIBLE_DEVICES: "0,1,2,3,4,5,6,7"
A100:
NCCL_DEBUG: info
A800:
NCCL_DEBUG: debug
```
=> [Core] Optimize the runner

README.md
This PR updates the installation instructions for ernergon.
=> [Doc] Update  energon readme

README.md
This PR updates the installation instructions for energon.
Cherry-pick from https://github.com/FlagOpen/FlagScale/pull/273
=> [CherryPick][Doc]Update energon readme

flagscale/inference/core/block_manager.py, flagscale/inference/core/data.py, flagscale/inference/core/llm_engine.py, flagscale/inference/core/logits_processor.py, flagscale/inference/core/model_runner.py, flagscale/inference/core/preprocess.py, flagscale/inference/core/sampling_metadata.py, flagscale/inference/core/sampling_params.py, flagscale/inference/core/scheduler.py, flagscale/inference/core/sequence.py
- Emu-gen：
```
python run.py -cp examples/emu/conf/ -cn config_gen.yaml
```
- Emu-chat:
```
python run.py -cp examples/emu/conf/ -cn config_chat.yaml
```
=> [CFG] update flagscale/inference/core for newest-vllm

flagscale/runner/runner_train.py, tools/datasets/llava_onevision/make_llava_ov_wds.sh
In this pr, we have made it compatible with the startup method of "master_add + master_port" in torchrun. 
Additionally, we have fixed the bug related to the node rank in data generation of llava onevision.
=> [LLaVA OV] Update torchrun and fix llava ov data making bug

examples/emu/conf/config_chat.yaml, examples/emu/conf/config_gen.yaml, examples/emu/conf/inference/inference_emu3_i2t.yaml, examples/emu/conf/inference/inference_emu3_t2i.yaml, flagscale/inference/arguments.py, flagscale/inference/core/block_manager.py, flagscale/inference/core/data.py, flagscale/inference/core/llm_engine.py, flagscale/inference/core/logits_processor.py, flagscale/inference/core/model_runner.py, flagscale/inference/core/preprocess.py, flagscale/inference/core/sampling_metadata.py, flagscale/inference/core/sampling_params.py, flagscale/inference/core/scheduler.py, flagscale/inference/core/sequence.py, flagscale/inference/core/single_step.py, flagscale/inference/inference_emu3.py, flagscale/runner/runner_inference.py
- update inference/core for vllm-v0.7.1
- fix the yaml management function with omegaconf
- fix the automatic identification function of the vllm installation path
=> [Core] Update inference/core for vllm-v0.7.1

flagscale/auto_tuner/utils.py
This PR fixes the import error for autotuner.
=> [BugFic] Fix runner import error of autotuner

flagscale/train/arguments.py, flagscale/train/hetero/p2p_communication.py, flagscale/train/hetero/parallel_context.py, flagscale/train/train.py, megatron/megatron/core/distributed/finalize_model_grads.py, megatron/megatron/core/optimizer/optimizer.py, megatron/megatron/core/pipeline_parallel/p2p_communication.py, megatron/megatron/core/timers.py, megatron/megatron/training/arguments.py, megatron/megatron/training/initialize.py, megatron/megatron/training/utils.py
Support the communication backend of [FlagCX](https://github.com/FlagOpen/FlagCX) and update the code when using cpu-based communication.
=> [Core] Support the communication backend of `FlagCX`

examples/deepseek/conf/config_auto_deepseek_v3.yaml, examples/qwen/conf/config_auto_tune_serve.yaml, flagscale/auto_tuner/__init__.py, flagscale/auto_tuner/generate.py, flagscale/auto_tuner/record/__init__.py, flagscale/auto_tuner/record/recorder.py, flagscale/auto_tuner/search/__init__.py, flagscale/auto_tuner/search/algorithm.py, flagscale/auto_tuner/search/searcher.py, flagscale/auto_tuner/tuner.py, flagscale/auto_tuner/utils.py, flagscale/metric/__init__.py, flagscale/metric/serve_metric.py, flagscale/runner/runner_base.py, flagscale/runner/runner_serve.py, flagscale/runner/runner_utils.py, flagscale/serve/core.py, run.py
=> [Serve] Add auto tuner serve

README.md
Update with the latest installation instructions.
=> [CI] Update README.md

README.md, examples/deepseek_r1/config_deepseek_r1.yaml, examples/deepseek_r1/serve/deepseek_r1.yaml
This PR adds deepseek_r1 config and adds the one-click serve command.
=> [Serve] Add deepseek_r1 serve config

.github/workflows/coverage-tests.yml, .github/workflows/functional-tests.yml, .github/workflows/report-clean.yml, .github/workflows/unit-tests.yml, docker/Dockerfile.cuda
Dockerfile updates bring about image updates, targeting the new image and updating the relevant code for running tests online.
=> [CI] Update to run tests online

README.md
=> [Misc] Fix a typo

README.md
=> [CherryPick][Misc] Fix a typo (#376)

.github/workflows/all-tests.yml, .github/workflows/coverage-tests.yml, .github/workflows/functional-tests.yml, .github/workflows/report-clean.yml, .github/workflows/unit-tests.yml, requirements/requirements-base.txt, requirements/requirements-dev.txt, tests/functional_tests/test_cases/serve/test_serve_base/conf/multiple_model.yaml, tests/functional_tests/test_cases/serve/test_serve_multiple_nodes/conf/multiple_model.yaml, tests/functional_tests/test_cases/serve/test_serve_vllm_model/conf/multiple_model.yaml, tests/scripts/unit_tests/config.yml, tests/scripts/unit_tests/test_subset.sh
1. Update some implementations and fix some errors.
2. Use the conda environment with flagscale train and flagscale reference for training and inference.
3. Add some basic dependency packages.
TODO:
Resolve the issue of errors in the serve test.
=> [CI] Update some implementations and fix some errors

.github/workflows/all-tests.yml, docker/Dockerfile.cuda, install/install-requirements.sh, requirements/requirements-base.txt, requirements/serving/requirements.txt, requirements/train/megatron/requirements-cuda.txt
1. Using the default source of apt.
2. Add some packages that serve needs.
3. Split some major installation steps.
=> [CI] Update some installation details

flagscale/runner/runner_serve.py, tests/functional_tests/test_cases/serve/test_serve_base/conf/multiple_model.yaml
=> [Serve] Fix CI test case

tools/patch/unpatch.py
1. Re-download FlagScale and unpatch again. 
2. Use the git config command to set your mailbox and name.
=> [TOOLS] Add a handling suggestion to the prompt for unpatch

flagscale/train/train_deepseek_v3.py, megatron/megatron/training/arguments.py
=> [Feature] Add MTP loss weight.

examples/qwen/conf/config_auto_tune_serve.yaml, examples/qwen/conf/config_qwen2.5_7b.yaml, examples/qwen/conf/serve/serve_qwen2.5_7b.yaml, flagscale/runner/auto_tuner/generate.py, flagscale/runner/auto_tuner/search/searcher.py, flagscale/runner/auto_tuner/tuner.py, flagscale/runner/runner_serve.py, flagscale/runner/utils.py
This PR increases the number of supported search spaces during automatic search, including block size, swap size, max_num_seqs, max_num_batched_tokens, etc. 
It optimizes the search space construction logic：
1. distinguishing between search spaces related to resource count and those unrelated to resources. 
2. supports user-defined sub-search spaces.
3. provides default search spaces.
=> [AutoTuner] Support more search space in serving

examples/minicpm_o_2.6/conf/config_minicpm_o_2.6.yaml, examples/minicpm_o_2.6/conf/serve/minicpm_o_2.6.yaml
=> Add minicmp_o_2.6 yaml

tools/patch/patch.py
This PR fixes a bug in the patch mechanism, preventing the deletion of other patches after generating a new patch.
=> [BugFix] Fix patch bug

tools/checkpoint/deepseek_v3/ckpt.py
support tp for deepseek checkpoint conversion
=> [Feature]support tp for deepseek checkpoint conversion

tools/patch/common.py, tools/patch/patch.py
Refer to https://github.com/FlagOpen/FlagScale/issues/447
=> [Tools] Fix patch encoding error

examples/emu/conf/config_chat.yaml, examples/emu/conf/config_gen.yaml, examples/emu/conf/inference/inference_emu3_t2i.yaml, flagscale/inference/core/block_manager.py, flagscale/inference/core/data.py, flagscale/inference/core/llm_engine.py, flagscale/inference/core/logits_processor.py, flagscale/inference/core/model_runner.py, flagscale/inference/core/preprocess.py, flagscale/inference/core/sampling_params.py, flagscale/inference/core/scheduler.py, flagscale/inference/core/sequence.py
- Emu-gen：
```
python run.py -cp examples/emu/conf/ -cn config_gen.yaml
```
- Emu-chat:
```
python run.py -cp examples/emu/conf/ -cn config_chat.yaml
```
=> [Core] update flagscale/inference/core for newest-vllm

communication/__init__.py, communication/communicator.py, setup.py
**Edge-cloud collaborative communicator to support robot agent system:**
1. Create an agent registration interface.
2. Implement a command sending interface.
3. Implement a command listening interface that is blocking rather than polling, offering better performance.
4. Develop data recording and access interfaces that support both partial and full access.
**Features:**
1. Utilizes Redis's publish/subscribe model at the lower level to achieve high-performance command publishing and responding, with response times reaching under 0.001 seconds.
2. Supports bidirectional communication between the brain and the robot, facilitating a closed-loop control path between brain commands and robot feedback.
**Usage:**
1. Include the source code.
2. Run: `pip install …
=> [Comm] Add a communicator for the edge-cloud collaborative

setup.py
This PR fixes the CLI issue, where the backend is now managed as a submodule, but previously it was still packaged as a subtree.
=> [BugFix] Fix the cli bug for submodule

setup.py
This PR fixes the bug when install gitpython in cli.
=> [BugFix] fix cli git error

tools/patch/patch.py
This PR fixes the patch bug when patch the modified files.
=> [BugFix]Fix patch error

tools/checkpoint/aquila/ckpt.py, tools/checkpoint/aquila/model.py, tools/checkpoint/convert.py, tools/checkpoint/deepseek_v3/ckpt.py, tools/checkpoint/llama/ckpt.py, tools/checkpoint/loader_mcore.py, tools/checkpoint/loader_transformers.py, tools/checkpoint/mistral/ckpt.py, tools/checkpoint/mixtral/ckpt.py, tools/checkpoint/mixtral/model.py, tools/checkpoint/saver_mcore.py, tools/checkpoint/saver_transformers.py, tools/checkpoint/utils.py
Update `tools/checkpoint/*` with newest Megatron-LM
=> Update CKPT Conversion Tool

tools/patch/patch.py
This pr fixed patch order error.
=> [BugFix] Fix patch order error

.github/workflows/all-tests.yml, .github/workflows/coverage-tests.yml, .github/workflows/functional-tests.yml, .github/workflows/unit-tests.yml, .pre-commit-config.yaml, tests/scripts/unit_tests/config.yml
1. Unpatch the corresponding package according to the type of test being run.
2. Adjust the import path of the package when running unit tests.
3. Skip the wrong test and mark it as TODO.
=> [CI] Update CI workflow with new patch mechanism

.github/workflows/all-tests.yml, flagscale/runner/runner_inference.py, run.py, tests/functional_tests/test_cases/inference/deepseek/conf/inference/tp2.yaml, tests/functional_tests/test_cases/inference/deepseek/conf/tp2.yaml, tests/functional_tests/test_cases/inference/deepseek/results_gold/tp2, tests/functional_tests/test_utils/test_equal.py, tests/scripts/functional_tests/config.yml, tests/scripts/functional_tests/test_all.sh, tests/scripts/functional_tests/test_task.sh
Add functional test:
1. Test type is inference
2. Model is deepseek
=> [CI][inference] Add functional test for inference

tools/patch/patch.py
This PR fixes bug for patching FlagScale.
=> [BugFix] Fix bug for patching FlagScale

hardware/README.md, hardware/README_CN.md, tools/patch/patch.py, tools/patch/unpatch.py
This PR updates the patching approach: instead of syncing back to the backends directory and applying patches there, it now directly diffs the submodule.
=> [Tools] Update patch method for hardware

tools/patch/patch.py
This PR fixes bug for patching llama.cpp
=> [BugFix] fix patch for llama.cpp

.github/workflows/all-tests.yml, .github/workflows/functional-tests.yml, .github/workflows/unit-tests.yml
When running the test, compile and install vllm to synchronize code changes to ensure that the latest vllm code is tested.
=> [CI][vllm] Reinstall vllm in workflow to synchronize code changes 

.github/workflows/all-tests.yml, tests/functional_tests/test_cases/inference/qwen3/conf/inference/tp2.yaml, tests/functional_tests/test_cases/inference/qwen3/conf/tp2.yaml, tests/functional_tests/test_cases/inference/qwen3/results_gold/tp2, tests/scripts/functional_tests/config.yml, tests/scripts/functional_tests/test_all.sh
Add functional test, qwen3 inference test
=> [CI][Inference] Add functional-test-inference qwen3

.github/workflows/all-tests.yml, .github/workflows/functional-tests.yml, .github/workflows/unit-tests.yml, flagscale/backends/vllm/vllm/v1/worker/gpu_model_runner.py, tests/functional_tests/test_cases/inference/deepseek_gems/conf/inference/tp2.yaml, tests/functional_tests/test_cases/inference/deepseek_gems/conf/tp2.yaml, tests/functional_tests/test_cases/inference/deepseek_gems/results_gold/tp2, tests/functional_tests/test_cases/inference/qwen3_gems/conf/inference/tp2.yaml, tests/functional_tests/test_cases/inference/qwen3_gems/conf/tp2.yaml, tests/functional_tests/test_cases/inference/qwen3_gems/results_gold/tp2, tests/scripts/functional_tests/config.yml, tests/scripts/functional_tests/test_all.sh
Modify the vllm source code to call FlagGems.
The added inference tests using FlagGems include:
1. deepseek_gems
2. qwen3_gems
=> [CI][FlagGems] Add inference tests using FlagGems

flagscale/runner/runner_serve.py
python run.py --config-path ./examples/deepseek_r1/conf --config-name serve **action=stop**
=> [Serve] Support to clear task by action=stop cross multiple nodes

flagscale/backends/vllm/vllm/v1/worker/gpu_model_runner.py
usage: export USE_FLAGGEMS=True <commands>
=> support FlagGems in vllm0.8+

tools/patch/unpatch.py
This PR fixed the bug of selecting the newest commit when backend commits is different.
=> [BugFix] Fix commit topo order bug

tools/patch/patch.py
This PR fixes the patch error when multi backends are `FlagScale xxx`.
=> [BugFix] Fix multi banckends for hardware patch error

flagscale/serve/run_fs_serve_vllm.py
Update engine args in multiple instance case
=> [Serve] Update engine args in multiple instance case

hardware/Metax_C550/FlagScale/diff.patch, hardware/Metax_C550/FlagScale/diff.yaml
=> [Metax_C550] Modify yamls for deepseek r1

hardware/patch_history.yaml
This PR adds patch history info for kunlunxin.
=> [Tools] Add kunlunxin patch history

hardware/patch_history.yaml
This PR updates patch hisotory.
=> [Tools] Update patch history

flagscale/backends/vllm/vllm/distributed/kv_transfer/kv_pipe/flagcx_p2p_nccl_pipe.py
**Overview:**
This pull request (PR) introduces a significant refactor of the FlagCX P2P pipe. 
**Key Changes:**
- **Dedicated Streams Implementation:** The P2P pipe now utilizes dedicated streams for send and receive operations.
- **Removal of Default Stream Dependence:** This change eliminates the reliance on the default stream.
**Problem Addressed:**
This refactoring resolves a hanging issue that arises when processing multiple requests during heterogeneous prefilling-decoding disaggregation. 
By implementing these changes, we aim to enhance the efficiency and reliability of the P2P operations within the system.
=> Use dedicated send/recv streams instead of default stream in FlagCX P2P pipe

.github/workflows/all-tests.yml, .github/workflows/functional-tests.yml, tests/functional_tests/test_utils/test_result.py
1. **Update Workflows**
**All-tests.yml**: Cancel the annotation of the inference testing module.
2. Addressing the randomness issue in inference
**test_result.py**: Resolve the issue of randomly generating '\ n' when reading lines to process data
=> [CICD][Fix] Update inference testing

.github/workflows/all-tests-nvidia.yml, tests/scripts/_gpu_check.sh, tests/scripts/unit_tests/test_subset.sh
1. Strict test flow failure detection, the goal is that any error, regardless of size, will throw an error/exception.
2. Update GPU detection method, the previous method could execute but would throw errors.
=> [CICD] Enhance Test Flow Error Detection and Update GPU Detection Method

.github/workflows/all-tests-metax.yml, .github/workflows/functional-tests-metax.yml, tests/scripts/_gpu_check.sh, tests/scripts/functional_tests/test_task.sh
Implement multi-chip GPU memory detection workflow, currently supporting NVIDIA and Metax. Detection process:
1. Detect chip type
2. Detect chip count
3. Check if the maximum GPU memory usage ratio across all chips exceeds 50%
- If it exceeds, wait
- If it doesn't exceed, return 0
Update corresponding workflow to trigger multi-chip testing pipeline when tests module changes
=> [CICD] Update the GPU Monitoring for Different Chips

examples/qwen3/conf/serve/8b.yaml
change qwen3_8b model path and port
=> [Model] change qwen3_8b model path and port

examples/qwen2_5/conf/serve/multiple_models.yaml, flagscale/serve/engine.py, tests/functional_tests/test_cases/serve/base/conf/serve/multiple_model.yaml
serve
`python run.py --config-path ./examples/qwen2_5/conf --config-name serve_multiple_models action=run`
call api
`curl -X POST -H "Content-Type: application/json" -d '{"prompt":"Introduce BruceLee"}' http://localhost:6701/generate`
=> [Serve] Support automatic scaling in composition of multiple models

.github/workflows/functional-tests-metax.yml, .github/workflows/functional-tests-nvidia.yml
Activate retry mechanism when download fails due to unstable network
=> [CICD] Timeout retry
